version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.18.0
    steps:
      - checkout
      - run: npm install
      - run:
          name: Run Start
          no_output_timeout: 30m
          command: npm run start
